.TH "readrbf" "" "" "" ""
.SH NAME
.PP
readrbf \- read a record\-based file and convert it to a known format
.SH SYNOPSIS
.PP
readrbf \-i file \- l layout [\-o format] [\-f file] [\-c] [\-O]
[\-\-br] [\-\-gf] [\-\-gr] [\-r file] [\-s n] [\-v] [\-p] [\-h]
.SH DESCRIPTION
.PP
This program is aimed at reading a record\-based file and converting it
to a human\-readable format.
It reads its settings from the rbf.xml configuration file located in the
current directory or ~/.rbf directory (linux) or the
%APPDATA%\\local\\rbf directory (Windows).
.SH OPTIONS
.PP
\-b : Benchmark: don\[aq]t write output file but just read input file.
.PP
\-\-br : Break records: try to break record into individual sub\-records
for better text presentation.
.PP
\-c : Validate layout structure.
.PP
\-\-check : check whether field patterns are matched
.PP
\-f file : Full path and name of a file to filter fields.
.PP
\-\-gf records/fields list : Grep fields: only write selected
records/fields.
.PP
\-\-gl pattern : Grep lines: only select lines matching the regex
pattern.
NB if "\-\-gf" is also specified, this \-\-gl comes first.
.PP
\-\-gr condition : Grep records: include records matching condition.
.PP
\-h : Print this help.
.PP
\-i file : Full path and name of the file to be read and converted.
.PP
\-l layout : Name of the input file layout.
This name is found is the configuration file rbf.xml.
.PP
\-o format : Name of the output file format.
Possible values are: html, tag, box, csv, txt, xlsx, sql, ident.
Defaulted to txt if not specified.
ident means the output file format is the same than the input one.
.PP
\-O : Write to standard output only.
.PP
\-p : Print out progress status.
.PP
\-r file : Full path and name of a file to filter records.
.PP
\-s n : Only convert the n\-first records.
.PP
\-v : Verbose: print out options.
